// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) 2025-2026 naskel.com

//! `PubSubType` class generation for C++
//!
//! Generates `TypeSupport` classes compatible with DDS implementations.

use crate::ast::Struct;
use crate::types::Annotation;
use std::fmt::Write;

/// Generates a `PubSubType` header for a struct
#[allow(clippy::too_many_lines)] // Full class template generation
pub fn generate_pubsub_type_header(s: &Struct) -> String {
    let type_name = &s.name;
    let class_name = format!("{}PubSubType", type_name);

    // Find @key fields for compute_key
    let key_fields: Vec<&str> = s
        .fields
        .iter()
        .filter(|f| f.annotations.iter().any(|a| matches!(a, Annotation::Key)))
        .map(|f| f.name.as_str())
        .collect();

    let has_key = !key_fields.is_empty();

    let mut out = String::new();

    // Header comment
    let _ = writeln!(out, "// PubSubType for {type_name}");
    out.push_str("// Generated by hddsgen\n\n");

    // Class declaration
    let _ = writeln!(out, "/// TypeSupport class for {type_name}");
    out.push_str("/// Provides DDS-compatible serialization/deserialization interface\n");
    let _ = writeln!(out, "class {class_name} {{");
    out.push_str("public:\n");
    let _ = writeln!(out, "    using type = {type_name};\n");
    let _ = writeln!(
        out,
        "    static constexpr const char* type_name() noexcept {{ return \"{type_name}\"; }}\n"
    );

    // serialize method
    out.push_str("    /// Serialize data to CDR2 little-endian format\n");
    let _ = writeln!(
        out,
        "    /// @param data Pointer to the {type_name} to serialize"
    );
    out.push_str("    /// @param buffer Output buffer\n");
    out.push_str("    /// @param buffer_size Size of output buffer\n");
    out.push_str("    /// @return Number of bytes written, or -1 on error\n");
    out.push_str(
        "    static int serialize(const void* data, std::uint8_t* buffer, std::size_t buffer_size) noexcept {\n",
    );
    out.push_str("        if (!data || !buffer) return -1;\n");
    let _ = writeln!(
        out,
        "        const auto* typed = static_cast<const {type_name}*>(data);"
    );
    out.push_str("        return typed->encode_cdr2_le(buffer, buffer_size);\n");
    out.push_str("    }\n\n");

    // deserialize method
    out.push_str("    /// Deserialize data from CDR2 little-endian format\n");
    out.push_str("    /// @param buffer Input buffer containing CDR2 data\n");
    out.push_str("    /// @param buffer_size Size of input buffer\n");
    let _ = writeln!(out, "    /// @param data Pointer to {type_name} to fill");
    out.push_str("    /// @return Number of bytes read, or -1 on error\n");
    out.push_str(
        "    static int deserialize(const std::uint8_t* buffer, std::size_t buffer_size, void* data) noexcept {\n",
    );
    out.push_str("        if (!buffer || !data) return -1;\n");
    let _ = writeln!(
        out,
        "        auto* typed = static_cast<{type_name}*>(data);"
    );
    out.push_str("        return typed->decode_cdr2_le(buffer, buffer_size);\n");
    out.push_str("    }\n\n");

    // calculate_serialized_size method
    out.push_str("    /// Calculate serialized size of data\n");
    let _ = writeln!(out, "    /// @param data Pointer to the {type_name}");
    out.push_str("    /// @return Serialized size in bytes, or 0 on error\n");
    out.push_str("    static std::size_t calculate_serialized_size(const void* data) noexcept {\n");
    out.push_str("        if (!data) return 0;\n");
    let _ = writeln!(
        out,
        "        const auto* typed = static_cast<const {type_name}*>(data);"
    );
    out.push_str("        // Fast path: stack buffer for typical types\n");
    out.push_str("        std::uint8_t stack_buf[16384];\n");
    out.push_str("        int size = typed->encode_cdr2_le(stack_buf, sizeof(stack_buf));\n");
    out.push_str("        if (size > 0) return static_cast<std::size_t>(size);\n");
    out.push_str("        // Heap fallback for large types (up to 16 MB)\n");
    out.push_str("        for (std::size_t cap = 65536; cap <= 16777216; cap *= 4) {\n");
    out.push_str("            auto* p = static_cast<std::uint8_t*>(std::malloc(cap));\n");
    out.push_str("            if (!p) return 0;\n");
    out.push_str("            size = typed->encode_cdr2_le(p, cap);\n");
    out.push_str("            std::free(p);\n");
    out.push_str("            if (size > 0) return static_cast<std::size_t>(size);\n");
    out.push_str("        }\n");
    out.push_str("        return 0;\n");
    out.push_str("    }\n\n");

    // create_data method
    let _ = writeln!(out, "    /// Create a new instance of {type_name}");
    let _ = writeln!(
        out,
        "    /// @return Pointer to newly allocated {type_name}, or nullptr on failure"
    );
    out.push_str("    static void* create_data() noexcept {\n");
    let _ = writeln!(out, "        return new (std::nothrow) {type_name}();");
    out.push_str("    }\n\n");

    // delete_data method
    let _ = writeln!(out, "    /// Delete an instance of {type_name}");
    let _ = writeln!(out, "    /// @param data Pointer to {type_name} to delete");
    out.push_str("    static void delete_data(void* data) noexcept {\n");
    let _ = writeln!(out, "        delete static_cast<{type_name}*>(data);");
    out.push_str("    }\n\n");

    // compute_key method (for instance identity)
    if has_key {
        out.push_str("    /// Compute instance key from @key fields\n");
        let _ = writeln!(out, "    /// @param data Pointer to {type_name}");
        out.push_str("    /// @param key_buffer Output buffer for key (16 bytes)\n");
        out.push_str("    /// @return true if key computed, false otherwise\n");
        out.push_str(
            "    static bool compute_key(const void* data, std::uint8_t key_buffer[16]) noexcept {\n",
        );
        out.push_str("        if (!data || !key_buffer) return false;\n");
        let _ = writeln!(
            out,
            "        const auto* typed = static_cast<const {type_name}*>(data);"
        );
        out.push_str("        // FNV-1a hash of key fields, expanded to 16 bytes\n");
        out.push_str("        std::uint64_t hash = 14695981039346656037ULL;\n");

        // Hash each key field
        for field in &key_fields {
            out.push_str("        {\n");
            let _ = writeln!(out, "            const auto& val = typed->{field};");
            out.push_str(
                "            const auto* ptr = reinterpret_cast<const std::uint8_t*>(&val);\n",
            );
            out.push_str("            for (std::size_t i = 0; i < sizeof(val); ++i) {\n");
            out.push_str("                hash ^= ptr[i];\n");
            out.push_str("                hash *= 1099511628211ULL;\n");
            out.push_str("            }\n");
            out.push_str("        }\n");
        }

        out.push_str("        // Expand hash to 16 bytes\n");
        out.push_str("        std::memset(key_buffer, 0, 16);\n");
        out.push_str("        std::memcpy(key_buffer, &hash, sizeof(hash));\n");
        out.push_str("        hash *= 1099511628211ULL;\n");
        out.push_str("        std::memcpy(key_buffer + 8, &hash, sizeof(hash));\n");
        out.push_str("        return true;\n");
        out.push_str("    }\n\n");

        out.push_str("    /// Check if this type has @key fields\n");
        out.push_str("    static constexpr bool has_key() noexcept { return true; }\n\n");
    } else {
        out.push_str("    /// Compute instance key (no @key fields defined)\n");
        out.push_str("    /// @return false (no key fields)\n");
        out.push_str(
            "    static bool compute_key(const void* /*data*/, std::uint8_t key_buffer[16]) noexcept {\n",
        );
        out.push_str("        std::memset(key_buffer, 0, 16);\n");
        out.push_str("        return false;\n");
        out.push_str("    }\n\n");

        out.push_str("    /// Check if this type has @key fields\n");
        out.push_str("    static constexpr bool has_key() noexcept { return false; }\n\n");
    }

    // Type properties
    out.push_str("    /// Check if type has bounded size\n");
    let _ = writeln!(
        out,
        "    static constexpr bool is_bounded() noexcept {{ return {}; }}\n",
        is_type_bounded(s)
    );
    out.push_str("    /// Check if type is plain (no pointers/dynamic allocation)\n");
    let _ = writeln!(
        out,
        "    static constexpr bool is_plain() noexcept {{ return {}; }}",
        is_type_plain(s)
    );

    // Close class
    out.push_str("};\n\n");

    out
}

/// Check if a struct has bounded size (no unbounded sequences/strings)
fn is_type_bounded(s: &Struct) -> &'static str {
    use crate::types::IdlType;

    for field in &s.fields {
        #[allow(clippy::unnested_or_patterns)] // More readable with separate arms
        match &field.field_type {
            IdlType::Sequence { bound: None, .. }
            | IdlType::Primitive(crate::types::PrimitiveType::String)
            | IdlType::Primitive(crate::types::PrimitiveType::WString)
            | IdlType::Map { bound: None, .. } => return "false",
            _ => {}
        }
    }
    "true"
}

/// Check if a struct is plain (no dynamic allocation needed)
fn is_type_plain(s: &Struct) -> &'static str {
    use crate::types::IdlType;

    for field in &s.fields {
        #[allow(clippy::unnested_or_patterns)] // More readable with separate arms
        match &field.field_type {
            IdlType::Sequence { .. }
            | IdlType::Primitive(crate::types::PrimitiveType::String)
            | IdlType::Primitive(crate::types::PrimitiveType::WString)
            | IdlType::Map { .. }
            | IdlType::Named(_) => return "false", // Named: conservative - may contain dynamic types
            _ => {}
        }
    }
    "true"
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Field, Struct};
    use crate::types::{IdlType, PrimitiveType};

    #[test]
    fn test_basic_pubsub_type() {
        let s = Struct {
            name: "HelloWorld".to_string(),
            fields: vec![
                Field {
                    name: "index".to_string(),
                    field_type: IdlType::Primitive(PrimitiveType::UInt32),
                    annotations: vec![],
                },
                Field {
                    name: "message".to_string(),
                    field_type: IdlType::Primitive(PrimitiveType::String),
                    annotations: vec![],
                },
            ],
            annotations: vec![],
            base_struct: None,
            extensibility: None,
        };

        let output = generate_pubsub_type_header(&s);
        assert!(output.contains("class HelloWorldPubSubType"));
        assert!(output.contains("using type = HelloWorld"));
        assert!(output.contains("serialize"));
        assert!(output.contains("deserialize"));
    }
}
