// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) 2025-2026 naskel.com

module Bits {
    @bit_bound(16)
    bitset Reg {
        bitfield<3> mode;
        bitfield<5> value, @position(4);
    };
    struct Sensors {
        @unit("m") @range(min=0, max=10000)
        int32_t distance;
        @min(0) @max(255)
        uint8_t level;
    };
};


