// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) 2025-2026 naskel.com

//! C header prelude generation.
//!
//! Generates include guards, standard includes, helper macros, and boilerplate.

use super::{helpers::push_fmt, CGenerator};

impl CGenerator {
    pub(super) fn header_prelude(include_fixed: bool, c_standard: super::CStandard) -> String {
        let mut out = String::new();
        Self::header_write_banner(&mut out);
        Self::header_write_includes(&mut out);
        Self::header_write_env_checks(&mut out, c_standard);
        Self::header_write_limits(&mut out);
        Self::header_write_error_codes(&mut out);
        Self::header_write_constants(&mut out);
        Self::header_write_helpers(&mut out, include_fixed, c_standard);
        out
    }

    fn header_write_banner(out: &mut String) {
        out.push_str("// Generated by hddsgen ");
        out.push_str(env!("HDDS_VERSION"));
        out.push_str("\n// DO NOT EDIT\n\n");
        out.push_str("#pragma once\n\n");
    }

    fn header_write_includes(out: &mut String) {
        out.push_str("#include <stdint.h>\n");
        out.push_str("#include <stddef.h>\n");
        out.push_str("#include <stdbool.h>\n");
        out.push_str("#include <wchar.h>\n");
        out.push_str("#include <string.h>\n\n");
        out.push_str("#include <limits.h>\n\n");
    }

    fn header_write_env_checks(out: &mut String, c_standard: super::CStandard) {
        // Endianness detection and byte-swap macros
        Self::header_write_endian_macros(out);

        // For now, we still require little-endian (swap macros ready for future BE support)
        out.push_str(
            "#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__)\n",
        );
        out.push_str("#error \"This generated header targets little-endian (CDR2 LE).\"\n");
        out.push_str("#endif\n");

        // _Static_assert is C11+; for C89/C99 we use a fallback or skip
        match c_standard {
            super::CStandard::C11 => {
                out.push_str("_Static_assert(CHAR_BIT == 8, \"CHAR_BIT must be 8\");\n");
                out.push_str("_Static_assert(sizeof(uint16_t) == 2, \"u16 size\");\n");
                out.push_str("_Static_assert(sizeof(uint32_t) == 4, \"u32 size\");\n");
                out.push_str("_Static_assert(sizeof(uint64_t) == 8, \"u64 size\");\n\n");
            }
            super::CStandard::C89 | super::CStandard::C99 => {
                // Use compile-time assertion macro that works in C89/C99
                out.push_str("/* Compile-time assertions (C89/C99 compatible) */\n");
                out.push_str("#define CDR_STATIC_ASSERT(cond, msg) \\\n");
                out.push_str("    typedef char static_assertion_##msg[(cond) ? 1 : -1]\n");
                out.push_str("CDR_STATIC_ASSERT(CHAR_BIT == 8, char_bit_must_be_8);\n");
                out.push_str("CDR_STATIC_ASSERT(sizeof(uint16_t) == 2, u16_size);\n");
                out.push_str("CDR_STATIC_ASSERT(sizeof(uint32_t) == 4, u32_size);\n");
                out.push_str("CDR_STATIC_ASSERT(sizeof(uint64_t) == 8, u64_size);\n\n");
            }
        }
    }

    fn header_write_endian_macros(out: &mut String) {
        out.push_str("/* Endianness detection */\n");
        out.push_str("#if defined(__BYTE_ORDER__)\n");
        out.push_str("  #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__\n");
        out.push_str("    #define CDR_LITTLE_ENDIAN 1\n");
        out.push_str("  #else\n");
        out.push_str("    #define CDR_LITTLE_ENDIAN 0\n");
        out.push_str("  #endif\n");
        out.push_str("#elif defined(_WIN32) || defined(__i386__) || defined(__x86_64__) || defined(__aarch64__)\n");
        out.push_str("  #define CDR_LITTLE_ENDIAN 1\n");
        out.push_str("#else\n");
        out.push_str("  #define CDR_LITTLE_ENDIAN 1  /* Assume LE; override if needed */\n");
        out.push_str("#endif\n\n");

        // Byte-swap primitives using compiler builtins when available
        out.push_str("/* Byte-swap primitives */\n");
        out.push_str("#if defined(__GNUC__) || defined(__clang__)\n");
        out.push_str("  #define CDR_BSWAP16(x) __builtin_bswap16(x)\n");
        out.push_str("  #define CDR_BSWAP32(x) __builtin_bswap32(x)\n");
        out.push_str("  #define CDR_BSWAP64(x) __builtin_bswap64(x)\n");
        out.push_str("#elif defined(_MSC_VER)\n");
        out.push_str("  #include <stdlib.h>\n");
        out.push_str("  #define CDR_BSWAP16(x) _byteswap_ushort(x)\n");
        out.push_str("  #define CDR_BSWAP32(x) _byteswap_ulong(x)\n");
        out.push_str("  #define CDR_BSWAP64(x) _byteswap_uint64(x)\n");
        out.push_str("#else\n");
        out.push_str("  /* Portable fallback */\n");
        out.push_str("  #define CDR_BSWAP16(x) ((uint16_t)( \\\n");
        out.push_str("      (((uint16_t)(x) & 0x00FFu) << 8) | \\\n");
        out.push_str("      (((uint16_t)(x) & 0xFF00u) >> 8)))\n");
        out.push_str("  #define CDR_BSWAP32(x) ((uint32_t)( \\\n");
        out.push_str("      (((uint32_t)(x) & 0x000000FFu) << 24) | \\\n");
        out.push_str("      (((uint32_t)(x) & 0x0000FF00u) <<  8) | \\\n");
        out.push_str("      (((uint32_t)(x) & 0x00FF0000u) >>  8) | \\\n");
        out.push_str("      (((uint32_t)(x) & 0xFF000000u) >> 24)))\n");
        out.push_str("  #define CDR_BSWAP64(x) ((uint64_t)( \\\n");
        out.push_str("      (((uint64_t)(x) & 0x00000000000000FFull) << 56) | \\\n");
        out.push_str("      (((uint64_t)(x) & 0x000000000000FF00ull) << 40) | \\\n");
        out.push_str("      (((uint64_t)(x) & 0x0000000000FF0000ull) << 24) | \\\n");
        out.push_str("      (((uint64_t)(x) & 0x00000000FF000000ull) <<  8) | \\\n");
        out.push_str("      (((uint64_t)(x) & 0x000000FF00000000ull) >>  8) | \\\n");
        out.push_str("      (((uint64_t)(x) & 0x0000FF0000000000ull) >> 24) | \\\n");
        out.push_str("      (((uint64_t)(x) & 0x00FF000000000000ull) >> 40) | \\\n");
        out.push_str("      (((uint64_t)(x) & 0xFF00000000000000ull) >> 56)))\n");
        out.push_str("#endif\n\n");

        // Host-to-little-endian and little-endian-to-host macros
        out.push_str("/* Host <-> Little-endian conversion */\n");
        out.push_str("#if CDR_LITTLE_ENDIAN\n");
        out.push_str("  #define CDR_HTOLE16(x) (x)\n");
        out.push_str("  #define CDR_HTOLE32(x) (x)\n");
        out.push_str("  #define CDR_HTOLE64(x) (x)\n");
        out.push_str("  #define CDR_LETOH16(x) (x)\n");
        out.push_str("  #define CDR_LETOH32(x) (x)\n");
        out.push_str("  #define CDR_LETOH64(x) (x)\n");
        out.push_str("#else\n");
        out.push_str("  #define CDR_HTOLE16(x) CDR_BSWAP16(x)\n");
        out.push_str("  #define CDR_HTOLE32(x) CDR_BSWAP32(x)\n");
        out.push_str("  #define CDR_HTOLE64(x) CDR_BSWAP64(x)\n");
        out.push_str("  #define CDR_LETOH16(x) CDR_BSWAP16(x)\n");
        out.push_str("  #define CDR_LETOH32(x) CDR_BSWAP32(x)\n");
        out.push_str("  #define CDR_LETOH64(x) CDR_BSWAP64(x)\n");
        out.push_str("#endif\n\n");
    }

    fn header_write_limits(out: &mut String) {
        out.push_str("#ifndef CDR_MAX_STRING\n");
        out.push_str("#define CDR_MAX_STRING (1u << 20)\n");
        out.push_str("#endif\n\n");
    }

    fn header_write_error_codes(out: &mut String) {
        out.push_str("#define CDR_OK 0\n");
        out.push_str("#define CDR_INVALID_DATA 1\n");
        out.push_str("#define CDR_UNEXPECTED_EOF 2\n");
        out.push_str("#define CDR_BUFFER_TOO_SMALL 3\n\n");
    }

    fn header_write_constants(out: &mut String) {
        // CDR2 alignment constants
        out.push_str("/* CDR2 alignment constants */\n");
        out.push_str("#define CDR_ALIGN_1 1\n");
        out.push_str("#define CDR_ALIGN_2 2\n");
        out.push_str("#define CDR_ALIGN_4 4\n");
        out.push_str("#define CDR_ALIGN_8 8\n\n");
        // CDR2 type sizes
        out.push_str("/* CDR2 type sizes */\n");
        out.push_str("#define CDR_SIZE_BOOL 1\n");
        out.push_str("#define CDR_SIZE_CHAR 1\n");
        out.push_str("#define CDR_SIZE_INT16 2\n");
        out.push_str("#define CDR_SIZE_INT32 4\n");
        out.push_str("#define CDR_SIZE_INT64 8\n");
        out.push_str("#define CDR_SIZE_FLOAT 4\n");
        out.push_str("#define CDR_SIZE_DOUBLE 8\n");
        out.push_str("#define CDR_SIZE_WCHAR 4\n");
        out.push_str("#define CDR_SIZE_FIXED128 16\n\n");
        // Unicode limits
        out.push_str("/* Unicode code point maximum */\n");
        out.push_str("#define CDR_UNICODE_MAX 0x10FFFFu\n\n");
    }

    fn header_write_helpers(out: &mut String, include_fixed: bool, c_standard: super::CStandard) {
        push_fmt(
            out,
            format_args!(
                "static inline size_t cdr_align(size_t offset, size_t align) {{\n    size_t mask = align - 1;\n    return (offset + mask) & ~mask;\n}}\n\n"
            ),
        );
        push_fmt(
            out,
            format_args!(
                "static inline int cdr_add(size_t* offset, size_t add) {{\n    size_t new_off = *offset + add;\n    if (new_off < *offset) {{ return -CDR_INVALID_DATA; }}\n    *offset = new_off;\n    return CDR_OK;\n}}\n\n"
            ),
        );
        push_fmt(
            out,
            format_args!(
                "static inline int cdr_pad(uint8_t* dst, size_t* off, size_t len, size_t align) {{\n    size_t aligned = cdr_align(*off, align);\n    if (aligned > len) {{ return -CDR_BUFFER_TOO_SMALL; }}\n    while (*off < aligned) {{\n        dst[*off] = 0;\n        ++(*off);\n    }}\n    return CDR_OK;\n}}\n\n"
            ),
        );
        push_fmt(
            out,
            format_args!(
                "static inline int cdr_need_write(size_t len, size_t offset, size_t need) {{\n    return (offset + need > len) ? -CDR_BUFFER_TOO_SMALL : CDR_OK;\n}}\n\n"
            ),
        );
        push_fmt(
            out,
            format_args!(
                "static inline int cdr_need_read(size_t len, size_t offset, size_t need) {{\n    return (offset + need > len) ? -CDR_UNEXPECTED_EOF : CDR_OK;\n}}\n\n"
            ),
        );
        push_fmt(
            out,
            format_args!(
                "static inline int cdr_skip(const uint8_t* src, size_t* off, size_t len, size_t align) {{\n    (void)src;\n    size_t a = cdr_align(*off, align);\n    if (a > *off) {{\n        int e = cdr_need_read(len, *off, a - *off);\n        if (e) {{ return e; }}\n        *off = a;\n    }}\n    return CDR_OK;\n}}\n\n"
            ),
        );

        if include_fixed {
            Self::header_write_fixed_helpers(out, c_standard);
        }
    }

    fn header_write_fixed_helpers(out: &mut String, c_standard: super::CStandard) {
        out.push_str("/* Fixed-point raw storage (CDR2 encodes 128-bit little-endian values) */\n");
        out.push_str("typedef struct {\n    int64_t high;\n    uint64_t low;\n} cdr_fixed128_t;\n");

        // Use appropriate static assert for C standard
        match c_standard {
            super::CStandard::C11 => {
                out.push_str(
                    "_Static_assert(sizeof(cdr_fixed128_t) == 16, \"cdr_fixed128_t size\");\n\n",
                );
            }
            super::CStandard::C89 | super::CStandard::C99 => {
                out.push_str(
                    "CDR_STATIC_ASSERT(sizeof(cdr_fixed128_t) == 16, cdr_fixed128_t_size);\n\n",
                );
            }
        }

        // For C89: declare loop variable at block start
        let is_c89 = matches!(c_standard, super::CStandard::C89);

        out.push_str("static inline void cdr_fixed128_to_le(const cdr_fixed128_t* value, uint8_t out[16]) {\n");
        if is_c89 {
            out.push_str("    size_t i;\n");
        }
        out.push_str("    uint64_t lo = value->low;\n");
        out.push_str("    uint64_t hi = (uint64_t)value->high;\n");
        if is_c89 {
            out.push_str("    for (i = 0; i < 8; ++i) {\n");
        } else {
            out.push_str("    for (size_t i = 0; i < 8; ++i) {\n");
        }
        out.push_str("        out[i] = (uint8_t)((lo >> (i * 8)) & 0xFFu);\n");
        out.push_str("        out[8 + i] = (uint8_t)((hi >> (i * 8)) & 0xFFu);\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        out.push_str("static inline void cdr_fixed128_from_le(cdr_fixed128_t* value, const uint8_t in[16]) {\n");
        if is_c89 {
            out.push_str("    size_t i;\n");
        }
        out.push_str("    uint64_t lo = 0;\n");
        out.push_str("    uint64_t hi = 0;\n");
        if is_c89 {
            out.push_str("    for (i = 0; i < 8; ++i) {\n");
        } else {
            out.push_str("    for (size_t i = 0; i < 8; ++i) {\n");
        }
        out.push_str("        lo |= ((uint64_t)in[i]) << (i * 8);\n");
        out.push_str("        hi |= ((uint64_t)in[8 + i]) << (i * 8);\n");
        out.push_str("    }\n");
        out.push_str("    value->low = lo;\n");
        out.push_str("    value->high = (int64_t)hi;\n");
        out.push_str("}\n\n");
    }
}
