// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) 2025-2026 naskel.com

//! Micro code generator for `no_std` embedded targets
//!
//! Generates Rust code compatible with `hdds_micro` crate.
//! Uses inline `CdrEncoder`/`CdrDecoder` instead of traits.
//!
//! # Supported IDL Constructs
//!
//! | Construct | Status | Notes |
//! |-----------|--------|-------|
//! | `struct` | ✅ Supported | With bounded strings/sequences via `heapless` |
//! | `enum` | ✅ Supported | Serialized as i32 |
//! | `union` | ✅ Supported | Discriminated unions |
//! | `module` | ✅ Supported | Mapped to Rust modules |
//! | `sequence<T, N>` | ✅ Supported | Uses `heapless::Vec<T, N>` |
//! | `string<N>` | ✅ Supported | Uses `heapless::String<N>` |
//! | `@key` | ✅ Supported | `compute_key()` method generated |
//!
//! # Unsupported Constructs (`no_std` Limitations)
//!
//! | Construct | Reason |
//! |-----------|--------|
//! | `map<K, V>` | Requires dynamic allocation (`HashMap`) |
//! | `bitset` | Not implemented for embedded targets |
//! | `bitmask` | Not implemented for embedded targets |
//! | `typedef` | Silently ignored |
//! | `const` | Silently ignored |
//! | Unbounded `sequence<T>` | No heap allocation available |
//! | Unbounded `string` | No heap allocation available |
//! | `@optional` | No `Option` equivalent without overhead |
//! | `@extensibility(MUTABLE)` | DHEADER/EMHEADER not implemented |
//!
//! Note: uninlined_format_args allowed here due to extensive `format!()` usage
//! in code generation that would require significant refactoring.

#![allow(clippy::uninlined_format_args)]
#![allow(clippy::format_push_string)]

use crate::ast::{Definition, Enum, IdlFile, Struct, Union, UnionLabel};
use crate::codegen::CodeGenerator;
use crate::error::Result;
use crate::types::{Annotation, IdlType, PrimitiveType};

mod decode;
mod encode;
mod types;

/// Configuration for micro code generation
#[derive(Debug, Clone)]
pub struct MicroConfig {
    /// Maximum length for `heapless::String<N>`
    pub max_string_len: usize,
    /// Maximum length for `heapless::Vec<T, N>`
    pub max_sequence_len: usize,
    /// Stack buffer size for encode/decode
    pub stack_buffer_size: usize,
}

impl Default for MicroConfig {
    fn default() -> Self {
        Self {
            max_string_len: 64,
            max_sequence_len: 32,
            stack_buffer_size: 256,
        }
    }
}

/// Generates `no_std` Rust code for `hdds_micro`
pub struct MicroGenerator {
    config: MicroConfig,
}

impl MicroGenerator {
    /// Creates a new micro generator with default configuration.
    #[must_use]
    pub fn new() -> Self {
        Self {
            config: MicroConfig::default(),
        }
    }

    /// Creates a new micro generator with custom configuration.
    #[must_use]
    pub const fn with_config(config: MicroConfig) -> Self {
        Self { config }
    }

    fn push_fmt(output: &mut String, args: std::fmt::Arguments<'_>) {
        use std::fmt::Write;
        let _ = write!(output, "{}", args);
    }
}

impl Default for MicroGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl MicroGenerator {
    /// Check if the AST uses types that require heapless (strings or sequences)
    fn ast_uses_heapless(ast: &IdlFile) -> bool {
        fn check_type(t: &IdlType) -> bool {
            match t {
                IdlType::Primitive(PrimitiveType::String | PrimitiveType::WString)
                | IdlType::Sequence { .. } => true,
                IdlType::Array { inner, .. } => check_type(inner),
                _ => false,
            }
        }

        fn check_def(def: &Definition) -> bool {
            match def {
                Definition::Struct(s) => s.fields.iter().any(|f| check_type(&f.field_type)),
                Definition::Module(m) => m.definitions.iter().any(check_def),
                _ => false,
            }
        }

        ast.definitions.iter().any(check_def)
    }
}

impl CodeGenerator for MicroGenerator {
    fn generate(&self, ast: &IdlFile) -> Result<String> {
        let mut output = String::new();

        // Check if we need heapless (strings or sequences)
        let needs_heapless = Self::ast_uses_heapless(ast);

        // Header
        output.push_str("// Generated by hdds_gen --target micro\n");
        output.push_str("// DO NOT EDIT\n\n");
        output.push_str("#![allow(dead_code, unused_imports)]\n\n");

        // Use hdds-micro crate for CDR (no inline code)
        output.push_str("// Re-export CDR types from hdds-micro\n");
        output.push_str("pub use hdds_micro::cdr::{CdrEncoder, CdrDecoder};\n");
        output.push_str("pub use hdds_micro::Error as CdrError;\n");

        if needs_heapless {
            output.push_str("pub use heapless;\n");
        }
        output.push('\n');

        // Generate definitions
        for def in &ast.definitions {
            match def {
                Definition::Module(m) => {
                    Self::push_fmt(&mut output, format_args!("pub mod {} {{\n", m.name));
                    output.push_str("    use super::*;\n\n");
                    for inner_def in &m.definitions {
                        match inner_def {
                            Definition::Struct(s) => {
                                let code = self.generate_struct(s);
                                for line in code.lines() {
                                    Self::push_fmt(&mut output, format_args!("    {}\n", line));
                                }
                            }
                            Definition::Enum(e) => {
                                let code = Self::generate_enum(e);
                                for line in code.lines() {
                                    Self::push_fmt(&mut output, format_args!("    {}\n", line));
                                }
                            }
                            Definition::Union(u) => {
                                let code = self.generate_union(u);
                                for line in code.lines() {
                                    Self::push_fmt(&mut output, format_args!("    {}\n", line));
                                }
                            }
                            _ => {}
                        }
                    }
                    output.push_str("}\n\n");
                }
                Definition::Struct(s) => output.push_str(&self.generate_struct(s)),
                Definition::Enum(e) => output.push_str(&Self::generate_enum(e)),
                Definition::Union(u) => output.push_str(&self.generate_union(u)),
                _ => {}
            }
        }

        Ok(output)
    }
}

impl MicroGenerator {
    /// Generate struct definition and encode/decode methods
    fn generate_struct(&self, s: &Struct) -> String {
        let mut output = String::new();

        // Struct definition
        Self::push_fmt(
            &mut output,
            format_args!("#[derive(Debug, Clone, PartialEq)]\n"),
        );
        Self::push_fmt(&mut output, format_args!("pub struct {} {{\n", s.name));

        for field in &s.fields {
            let rust_type = self.type_to_rust_micro(&field.field_type);
            Self::push_fmt(
                &mut output,
                format_args!("    pub {}: {},\n", field.name, rust_type),
            );
        }
        output.push_str("}\n\n");

        // Calculate max encoded size
        let max_size = self.calculate_max_size(s);
        Self::push_fmt(
            &mut output,
            format_args!(
                "impl {} {{\n    pub const ENCODED_SIZE_MAX: usize = {};\n\n",
                s.name, max_size
            ),
        );

        // Generate encode method
        output.push_str(&Self::generate_encode_method(s));

        // Generate decode method
        output.push_str(&self.generate_decode_method(s));

        // Generate compute_key method
        output.push_str(&Self::generate_compute_key_method(s));

        output.push_str("}\n\n");
        output
    }

    /// Generate enum definition
    fn generate_enum(e: &Enum) -> String {
        let mut output = String::new();

        Self::push_fmt(
            &mut output,
            format_args!("#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]\n"),
        );
        Self::push_fmt(&mut output, format_args!("#[repr(u32)]\n"));
        Self::push_fmt(&mut output, format_args!("pub enum {} {{\n", e.name));

        for (i, variant) in e.variants.iter().enumerate() {
            // First variant gets #[default] attribute
            let default_attr = if i == 0 { "    #[default]\n" } else { "" };
            if let Some(val) = variant.value {
                Self::push_fmt(
                    &mut output,
                    format_args!("{}    {} = {},\n", default_attr, variant.name, val),
                );
            } else {
                Self::push_fmt(
                    &mut output,
                    format_args!("{}    {} = {},\n", default_attr, variant.name, i),
                );
            }
        }
        output.push_str("}\n\n");

        // Impl encode/decode for enum
        Self::push_fmt(&mut output, format_args!("impl {} {{\n", e.name));
        output
            .push_str("    pub fn encode(&self, enc: &mut CdrEncoder) -> Result<(), CdrError> {\n");
        output.push_str("        enc.encode_u32(*self as u32)\n");
        output.push_str("    }\n\n");

        output.push_str("    pub fn decode(dec: &mut CdrDecoder) -> Result<Self, CdrError> {\n");
        output.push_str("        let v = dec.decode_u32()?;\n");
        output.push_str("        match v {\n");
        for (i, variant) in e.variants.iter().enumerate() {
            // @audit-ok: safe cast - enum variant index always << i64::MAX
            #[allow(clippy::cast_possible_wrap)]
            let val = variant.value.unwrap_or(i as i64);
            Self::push_fmt(
                &mut output,
                format_args!("            {} => Ok(Self::{}),\n", val, variant.name),
            );
        }
        output.push_str("            _ => Err(CdrError::InvalidEncoding),\n");
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");

        output
    }

    /// Generate union definition and encode/decode methods
    fn generate_union(&self, u: &Union) -> String {
        let mut output = String::new();

        // Union as Rust enum with tuple variants
        Self::push_fmt(
            &mut output,
            format_args!("#[derive(Debug, Clone, PartialEq)]\n"),
        );
        Self::push_fmt(&mut output, format_args!("pub enum {} {{\n", u.name));

        for (idx, case) in u.cases.iter().enumerate() {
            let variant_name = Self::union_variant_name(&case.field.name, idx);
            let field_type = self.type_to_rust_micro(&case.field.field_type);
            Self::push_fmt(
                &mut output,
                format_args!("    {}({}),\n", variant_name, field_type),
            );
        }
        output.push_str("}\n\n");

        // Get discriminator type info
        let _disc_type = self.type_to_rust_micro(&u.discriminator);
        let disc_encode = Self::discriminator_encode_call(&u.discriminator);
        let disc_decode = Self::discriminator_decode_call(&u.discriminator);

        // Encode method
        Self::push_fmt(&mut output, format_args!("impl {} {{\n", u.name));
        output
            .push_str("    pub fn encode(&self, enc: &mut CdrEncoder) -> Result<(), CdrError> {\n");
        output.push_str("        match self {\n");

        for (idx, case) in u.cases.iter().enumerate() {
            let variant_name = Self::union_variant_name(&case.field.name, idx);
            let disc_value = Self::get_discriminator_value(case, &u.discriminator, u);

            Self::push_fmt(
                &mut output,
                format_args!("            Self::{}(v) => {{\n", variant_name),
            );
            Self::push_fmt(
                &mut output,
                format_args!(
                    "                {}?;\n",
                    disc_encode.replace("{}", &disc_value)
                ),
            );

            // Encode the value based on type
            let encode_call = Self::generate_value_encode("v", &case.field.field_type);
            Self::push_fmt(&mut output, format_args!("                {}", encode_call));
            output.push_str("            }\n");
        }
        output.push_str("        }\n");
        output.push_str("        Ok(())\n");
        output.push_str("    }\n\n");

        // Decode method
        output.push_str("    pub fn decode(dec: &mut CdrDecoder) -> Result<Self, CdrError> {\n");
        Self::push_fmt(
            &mut output,
            format_args!("        let disc = {}?;\n", disc_decode),
        );
        output.push_str("        match disc {\n");

        for (idx, case) in u.cases.iter().enumerate() {
            let variant_name = Self::union_variant_name(&case.field.name, idx);
            let disc_value = Self::get_discriminator_value(case, &u.discriminator, u);

            // Handle default case
            let is_default = case.labels.iter().any(|l| matches!(l, UnionLabel::Default));

            if is_default {
                output.push_str("            _ => {\n");
            } else {
                Self::push_fmt(
                    &mut output,
                    format_args!("            {} => {{\n", disc_value),
                );
            }

            let decode_call = self.generate_value_decode(&case.field.field_type);
            Self::push_fmt(
                &mut output,
                format_args!(
                    "                Ok(Self::{}({}))\n",
                    variant_name, decode_call
                ),
            );
            output.push_str("            }\n");
        }

        // Add catch-all only if discriminator is not an enum (enums may be exhaustive)
        // or if there's no default case and the enum might have unknown values
        let has_default = u
            .cases
            .iter()
            .any(|c| c.labels.iter().any(|l| matches!(l, UnionLabel::Default)));
        let disc_is_enum = matches!(u.discriminator, IdlType::Named(_));
        // For enum discriminators, rustc will warn about unreachable patterns
        // if all variants are covered, so only add wildcard for non-enum discs
        if !has_default && !disc_is_enum {
            output.push_str("            _ => Err(CdrError::InvalidEncoding),\n");
        }

        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");

        output
    }

    fn union_variant_name(field_name: &str, idx: usize) -> String {
        // Convert to CamelCase: foo_bar -> FooBar
        let mut result = String::new();
        let mut capitalize_next = true;

        for c in field_name.chars() {
            if c == '_' {
                capitalize_next = true;
            } else if capitalize_next {
                result.push(c.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                result.push(c);
            }
        }

        if result.chars().next().is_none_or(|c| !c.is_alphabetic()) {
            format!("Case{idx}")
        } else {
            result
        }
    }

    fn discriminator_encode_call(disc_type: &IdlType) -> String {
        match disc_type {
            IdlType::Named(name) => format!("{name}::encode(&{{}}, enc)"),
            IdlType::Primitive(p) => Self::primitive_encode_call("{}", p),
            _ => "enc.encode_u32({})".to_string(),
        }
    }

    fn discriminator_decode_call(disc_type: &IdlType) -> String {
        match disc_type {
            IdlType::Named(name) => format!("{name}::decode(dec)"),
            IdlType::Primitive(p) => Self::primitive_decode_call(p),
            _ => "dec.decode_u32()".to_string(),
        }
    }

    fn get_discriminator_value(
        case: &crate::ast::UnionCase,
        disc_type: &IdlType,
        union: &crate::ast::Union,
    ) -> String {
        // Get the first non-default label
        for label in &case.labels {
            if let UnionLabel::Value(v) = label {
                if let IdlType::Named(enum_name) = disc_type {
                    return format!("{}::{}", enum_name, v);
                }
                return v.clone();
            }
        }
        // Default case: find non-colliding discriminant
        Self::disc_default_value(disc_type, union)
    }

    fn disc_default_value(disc_type: &IdlType, union: &crate::ast::Union) -> String {
        let mut used: Vec<i64> = Vec::new();
        let is_enum_disc = matches!(disc_type, IdlType::Named(_));
        let mut next_enum_ordinal: i64 = 0;
        for case in &union.cases {
            for label in &case.labels {
                if let UnionLabel::Value(v) = label {
                    if let Ok(n) = v.parse::<i64>() {
                        used.push(n);
                    } else if is_enum_disc {
                        used.push(next_enum_ordinal);
                        next_enum_ordinal += 1;
                    }
                }
            }
        }
        if matches!(disc_type, IdlType::Primitive(PrimitiveType::Boolean)) {
            return if used.contains(&0) {
                "true".to_string()
            } else {
                "false".to_string()
            };
        }
        let mut candidate: i64 = 0;
        loop {
            if !used.contains(&candidate) {
                return candidate.to_string();
            }
            candidate += 1;
            if candidate > 0x7FFF_FFFF {
                break;
            }
        }
        "0".to_string()
    }

    fn generate_value_encode(var: &str, t: &IdlType) -> String {
        match t {
            IdlType::Primitive(p) => {
                // For primitives in unions, we have a reference, so dereference
                let call = Self::primitive_encode_call(&format!("*{}", var), p);
                format!("{}?;\n", call)
            }
            IdlType::Named(_) => {
                format!("{}.encode(enc)?;\n", var)
            }
            IdlType::Sequence { inner, bound: _ } => {
                if **inner == IdlType::Primitive(PrimitiveType::Char) {
                    format!("enc.encode_string(&{})?;\n", var)
                } else {
                    let mut out = String::new();
                    out.push_str(&format!("enc.encode_seq_len({}.len())?;\n", var));
                    out.push_str(&format!("                for item in {}.iter() {{\n", var));
                    match &**inner {
                        IdlType::Primitive(p) => {
                            let encode_call = Self::primitive_encode_call("*item", p);
                            out.push_str(&format!("                    {}?;\n", encode_call));
                        }
                        _ => {
                            out.push_str("                    item.encode(enc)?;\n");
                        }
                    }
                    out.push_str("                }\n");
                    out
                }
            }
            IdlType::Array { inner, size } => {
                let mut out = format!("for i in 0..{} {{\n", size);
                match &**inner {
                    IdlType::Primitive(p) => {
                        let encode_call = Self::primitive_encode_call(&format!("{}[i]", var), p);
                        out.push_str(&format!("                    {}?;\n", encode_call));
                    }
                    _ => {
                        out.push_str(&format!("                    {}[i].encode(enc)?;\n", var));
                    }
                }
                out.push_str("                }\n");
                out
            }
            IdlType::Map { .. } => "// Map not supported in no_std\n".to_string(),
        }
    }

    fn generate_value_decode(&self, t: &IdlType) -> String {
        match t {
            IdlType::Primitive(p) => {
                let call = Self::primitive_decode_call(p);
                format!("{}?", call)
            }
            IdlType::Named(type_name) => {
                format!("{}::decode(dec)?", type_name)
            }
            IdlType::Sequence { inner, bound } => {
                if **inner == IdlType::Primitive(PrimitiveType::Char) {
                    "dec.decode_string()?".to_string()
                } else {
                    // @audit-ok: safe cast - config values are bounded by design (default: 32)
                    #[allow(clippy::cast_possible_truncation)]
                    let capacity = bound.unwrap_or(self.config.max_sequence_len as u32);
                    let inner_decode = match &**inner {
                        IdlType::Primitive(p) => format!("{}?", Self::primitive_decode_call(p)),
                        IdlType::Named(type_name) => format!("{}::decode(dec)?", type_name),
                        _ => "Default::default()".to_string(),
                    };
                    format!(
                        "{{ let len = dec.decode_seq_len()?; let mut v = heapless::Vec::<_, {}>::new(); for _ in 0..len {{ v.push({}).map_err(|_| CdrError::BufferTooSmall)?; }} v }}",
                        capacity, inner_decode
                    )
                }
            }
            IdlType::Array { inner, size } => {
                let inner_decode = match &**inner {
                    IdlType::Primitive(p) => format!("{}?", Self::primitive_decode_call(p)),
                    IdlType::Named(type_name) => format!("{}::decode(dec)?", type_name),
                    _ => "Default::default()".to_string(),
                };
                format!(
                    "{{ let mut arr = [Default::default(); {}]; for i in 0..{} {{ arr[i] = {}; }} arr }}",
                    size, size, inner_decode
                )
            }
            IdlType::Map { .. } => "Default::default() /* Map not supported */".to_string(),
        }
    }

    /// Map IDL type to Rust type for micro target
    fn type_to_rust_micro(&self, idl_type: &IdlType) -> String {
        match idl_type {
            IdlType::Primitive(p) => self.primitive_to_rust(p),
            IdlType::Named(name) => name.clone(),
            IdlType::Array { inner, size } => {
                format!("[{}; {}]", self.type_to_rust_micro(inner), size)
            }
            IdlType::Sequence { inner, bound } => {
                // Check if this is a bounded string (string<N> -> sequence<char, N>)
                if **inner == IdlType::Primitive(PrimitiveType::Char) {
                    // @audit-ok: safe cast - config values are bounded by design (default: 64)
                    #[allow(clippy::cast_possible_truncation)]
                    let capacity = bound.unwrap_or(self.config.max_string_len as u32);
                    return format!("heapless::String<{}>", capacity);
                }
                // Regular sequence
                let inner_type = self.type_to_rust_micro(inner);
                // @audit-ok: safe cast - config values are bounded by design (default: 32)
                #[allow(clippy::cast_possible_truncation)]
                let capacity = bound.unwrap_or(self.config.max_sequence_len as u32);
                format!("heapless::Vec<{}, {}>", inner_type, capacity)
            }
            IdlType::Map { .. } => "/* map not supported in no_std */".to_string(),
        }
    }

    fn primitive_to_rust(&self, p: &PrimitiveType) -> String {
        match p {
            PrimitiveType::Octet | PrimitiveType::UInt8 | PrimitiveType::Char => {
                "u8".to_string() // Char is ASCII
            }
            PrimitiveType::Int8 => "i8".to_string(),
            PrimitiveType::Boolean => "bool".to_string(),
            PrimitiveType::Short | PrimitiveType::Int16 => "i16".to_string(),
            PrimitiveType::UnsignedShort | PrimitiveType::UInt16 => "u16".to_string(),
            PrimitiveType::Long | PrimitiveType::Int32 => "i32".to_string(),
            PrimitiveType::UnsignedLong | PrimitiveType::UInt32 | PrimitiveType::WChar => {
                "u32".to_string()
            }
            PrimitiveType::LongLong | PrimitiveType::Int64 => "i64".to_string(),
            PrimitiveType::UnsignedLongLong | PrimitiveType::UInt64 => "u64".to_string(),
            PrimitiveType::Float => "f32".to_string(),
            PrimitiveType::Double | PrimitiveType::LongDouble => "f64".to_string(),
            PrimitiveType::String | PrimitiveType::WString => {
                // Unbounded string -> heapless::String with default capacity
                format!("heapless::String<{}>", self.config.max_string_len)
            }
            PrimitiveType::Void => "()".to_string(),
            PrimitiveType::Fixed { .. } => "i128".to_string(),
        }
    }

    fn calculate_max_size(&self, s: &Struct) -> usize {
        let mut size = 0;
        for field in &s.fields {
            size += self.type_max_size(&field.field_type);
            // Add worst-case padding
            let align = Self::type_alignment(&field.field_type);
            if align > 1 {
                size += align - 1;
            }
        }
        size
    }

    fn type_max_size(&self, t: &IdlType) -> usize {
        match t {
            IdlType::Primitive(p) => self.primitive_size(p),
            IdlType::Named(_) => 64, // Conservative estimate
            IdlType::Array { inner, size } => self.type_max_size(inner) * (*size as usize),
            IdlType::Sequence { .. } => 4 + self.config.max_sequence_len * 8,
            IdlType::Map { .. } => 256,
        }
    }

    const fn primitive_size(&self, p: &PrimitiveType) -> usize {
        match p {
            PrimitiveType::Octet
            | PrimitiveType::UInt8
            | PrimitiveType::Int8
            | PrimitiveType::Char
            | PrimitiveType::Boolean => 1,
            PrimitiveType::Short
            | PrimitiveType::UnsignedShort
            | PrimitiveType::Int16
            | PrimitiveType::UInt16 => 2,
            PrimitiveType::Long
            | PrimitiveType::UnsignedLong
            | PrimitiveType::Int32
            | PrimitiveType::UInt32
            | PrimitiveType::Float
            | PrimitiveType::WChar => 4,
            PrimitiveType::LongLong
            | PrimitiveType::UnsignedLongLong
            | PrimitiveType::Int64
            | PrimitiveType::UInt64
            | PrimitiveType::Double
            | PrimitiveType::LongDouble => 8,
            PrimitiveType::String | PrimitiveType::WString => 4 + self.config.max_string_len + 1,
            PrimitiveType::Void => 0,
            PrimitiveType::Fixed { .. } => 16,
        }
    }

    fn type_alignment(t: &IdlType) -> usize {
        match t {
            IdlType::Primitive(p) => Self::primitive_alignment(p),
            IdlType::Named(_) | IdlType::Sequence { .. } | IdlType::Map { .. } => 4,
            IdlType::Array { inner, .. } => Self::type_alignment(inner),
        }
    }

    const fn primitive_alignment(p: &PrimitiveType) -> usize {
        match p {
            PrimitiveType::Octet
            | PrimitiveType::UInt8
            | PrimitiveType::Int8
            | PrimitiveType::Char
            | PrimitiveType::Boolean
            | PrimitiveType::Void
            | PrimitiveType::Fixed { .. } => 1,
            PrimitiveType::Short
            | PrimitiveType::UnsignedShort
            | PrimitiveType::Int16
            | PrimitiveType::UInt16 => 2,
            PrimitiveType::Long
            | PrimitiveType::UnsignedLong
            | PrimitiveType::Int32
            | PrimitiveType::UInt32
            | PrimitiveType::Float
            | PrimitiveType::WChar
            | PrimitiveType::String
            | PrimitiveType::WString => 4,
            PrimitiveType::LongLong
            | PrimitiveType::UnsignedLongLong
            | PrimitiveType::Int64
            | PrimitiveType::UInt64
            | PrimitiveType::Double
            | PrimitiveType::LongDouble => 8,
        }
    }

    /// Generate encode method for struct
    fn generate_encode_method(s: &Struct) -> String {
        let mut output = String::new();
        output
            .push_str("    pub fn encode(&self, enc: &mut CdrEncoder) -> Result<(), CdrError> {\n");

        for field in &s.fields {
            output.push_str(&Self::generate_field_encode(&field.name, &field.field_type));
        }

        output.push_str("        Ok(())\n");
        output.push_str("    }\n\n");
        output
    }

    fn generate_field_encode(name: &str, t: &IdlType) -> String {
        match t {
            IdlType::Primitive(p) => Self::generate_primitive_encode(name, p),
            IdlType::Named(_type_name) => {
                format!("        self.{}.encode(enc)?;\n", name)
            }
            IdlType::Array { inner, size } => {
                let mut out = String::new();
                Self::push_fmt(&mut out, format_args!("        for i in 0..{} {{\n", size));
                match &**inner {
                    IdlType::Primitive(p) => {
                        let encode_call =
                            Self::primitive_encode_call(&format!("self.{}[i]", name), p);
                        Self::push_fmt(&mut out, format_args!("            {}?;\n", encode_call));
                    }
                    _ => {
                        Self::push_fmt(
                            &mut out,
                            format_args!("            self.{}[i].encode(enc)?;\n", name),
                        );
                    }
                }
                out.push_str("        }\n");
                out
            }
            IdlType::Sequence { inner, bound: _ } => {
                // Check if it's a bounded string (sequence<char, N>)
                if **inner == IdlType::Primitive(PrimitiveType::Char) {
                    return format!("        enc.encode_string(&self.{})?;\n", name);
                }
                // Regular sequence
                let mut out = String::new();
                Self::push_fmt(
                    &mut out,
                    format_args!("        enc.encode_seq_len(self.{}.len())?;\n", name),
                );
                Self::push_fmt(
                    &mut out,
                    format_args!("        for item in self.{}.iter() {{\n", name),
                );
                match &**inner {
                    IdlType::Primitive(p) => {
                        let encode_call = Self::primitive_encode_call("*item", p);
                        Self::push_fmt(&mut out, format_args!("            {}?;\n", encode_call));
                    }
                    _ => {
                        out.push_str("            item.encode(enc)?;\n");
                    }
                }
                out.push_str("        }\n");
                out
            }
            IdlType::Map { .. } => {
                format!("        // map not supported in no_std: {}\n", name)
            }
        }
    }

    fn generate_primitive_encode(name: &str, p: &PrimitiveType) -> String {
        let call = Self::primitive_encode_call(&format!("self.{}", name), p);
        format!("        {}?;\n", call)
    }

    fn primitive_encode_call(expr: &str, p: &PrimitiveType) -> String {
        match p {
            PrimitiveType::Octet | PrimitiveType::UInt8 | PrimitiveType::Char => {
                format!("enc.encode_u8({})", expr)
            }
            PrimitiveType::Int8 => format!("enc.encode_i8({})", expr),
            PrimitiveType::Boolean => format!("enc.encode_bool({})", expr),
            PrimitiveType::Short | PrimitiveType::Int16 => format!("enc.encode_i16({})", expr),
            PrimitiveType::UnsignedShort | PrimitiveType::UInt16 => {
                format!("enc.encode_u16({})", expr)
            }
            PrimitiveType::Long | PrimitiveType::Int32 => format!("enc.encode_i32({})", expr),
            PrimitiveType::UnsignedLong | PrimitiveType::UInt32 => {
                format!("enc.encode_u32({})", expr)
            }
            PrimitiveType::LongLong | PrimitiveType::Int64 => format!("enc.encode_i64({})", expr),
            PrimitiveType::UnsignedLongLong | PrimitiveType::UInt64 => {
                format!("enc.encode_u64({})", expr)
            }
            PrimitiveType::Float => format!("enc.encode_f32({})", expr),
            PrimitiveType::Double | PrimitiveType::LongDouble => {
                format!("enc.encode_f64({})", expr)
            }
            PrimitiveType::WChar => format!("enc.encode_u32({})", expr),
            PrimitiveType::String | PrimitiveType::WString => {
                format!("enc.encode_string(&{})", expr)
            }
            _ => format!("/* unsupported: {} */", expr),
        }
    }

    /// Generate decode method for struct
    fn generate_decode_method(&self, s: &Struct) -> String {
        let mut output = String::new();
        output.push_str("    pub fn decode(dec: &mut CdrDecoder) -> Result<Self, CdrError> {\n");
        output.push_str("        Ok(Self {\n");

        for field in &s.fields {
            output.push_str(&self.generate_field_decode(&field.name, &field.field_type));
        }

        output.push_str("        })\n");
        output.push_str("    }\n");
        output
    }

    fn generate_field_decode(&self, name: &str, t: &IdlType) -> String {
        match t {
            IdlType::Primitive(p) => {
                let call = Self::primitive_decode_call(p);
                format!("            {}: {}?,\n", name, call)
            }
            IdlType::Named(type_name) => {
                format!("            {}: {}::decode(dec)?,\n", name, type_name)
            }
            IdlType::Array { inner, size } => {
                // For arrays, we need to decode element by element
                let mut out = String::new();
                Self::push_fmt(&mut out, format_args!("            {}: {{\n", name));
                Self::push_fmt(
                    &mut out,
                    format_args!(
                        "                let mut arr = [Default::default(); {}];\n",
                        size
                    ),
                );
                out.push_str("                for i in 0..arr.len() {\n");
                match &**inner {
                    IdlType::Primitive(p) => {
                        let decode_call = Self::primitive_decode_call(p);
                        Self::push_fmt(
                            &mut out,
                            format_args!("                    arr[i] = {}?;\n", decode_call),
                        );
                    }
                    IdlType::Named(type_name) => {
                        Self::push_fmt(
                            &mut out,
                            format_args!(
                                "                    arr[i] = {}::decode(dec)?;\n",
                                type_name
                            ),
                        );
                    }
                    _ => {
                        out.push_str(
                            "                    // complex array element: not yet supported\n",
                        );
                    }
                }
                out.push_str("                }\n");
                out.push_str("                arr\n");
                out.push_str("            },\n");
                out
            }
            IdlType::Sequence { inner, bound } => {
                // Check if it's a bounded string (sequence<char, N>)
                if **inner == IdlType::Primitive(PrimitiveType::Char) {
                    return format!("            {}: dec.decode_string()?,\n", name);
                }
                // Regular sequence - decode element by element
                // @audit-ok: safe cast - config values are bounded by design (default: 32)
                #[allow(clippy::cast_possible_truncation)]
                let capacity = bound.unwrap_or(self.config.max_sequence_len as u32);
                let mut out = String::new();
                Self::push_fmt(&mut out, format_args!("            {}: {{\n", name));
                out.push_str("                let len = dec.decode_seq_len()?;\n");
                Self::push_fmt(
                    &mut out,
                    format_args!(
                        "                let mut v = heapless::Vec::<_, {}>::new();\n",
                        capacity
                    ),
                );
                out.push_str("                for _ in 0..len {\n");
                match &**inner {
                    IdlType::Primitive(p) => {
                        let decode_call = Self::primitive_decode_call(p);
                        Self::push_fmt(
                            &mut out,
                            format_args!(
                                "                    v.push({}?).map_err(|_| CdrError::BufferTooSmall)?;\n",
                                decode_call
                            ),
                        );
                    }
                    IdlType::Named(type_name) => {
                        Self::push_fmt(
                            &mut out,
                            format_args!(
                                "                    v.push({}::decode(dec)?).map_err(|_| CdrError::BufferTooSmall)?;\n",
                                type_name
                            ),
                        );
                    }
                    _ => {
                        out.push_str(
                            "                    // complex sequence element: not yet supported\n",
                        );
                    }
                }
                out.push_str("                }\n");
                out.push_str("                v\n");
                out.push_str("            },\n");
                out
            }
            IdlType::Map { .. } => {
                format!(
                    "            {}: Default::default(), // map not supported in no_std\n",
                    name
                )
            }
        }
    }

    fn primitive_decode_call(p: &PrimitiveType) -> String {
        match p {
            PrimitiveType::Octet | PrimitiveType::UInt8 | PrimitiveType::Char => {
                "dec.decode_u8()".to_string()
            }
            PrimitiveType::Int8 => "dec.decode_i8()".to_string(),
            PrimitiveType::Boolean => "dec.decode_bool()".to_string(),
            PrimitiveType::Short | PrimitiveType::Int16 => "dec.decode_i16()".to_string(),
            PrimitiveType::UnsignedShort | PrimitiveType::UInt16 => "dec.decode_u16()".to_string(),
            PrimitiveType::Long | PrimitiveType::Int32 => "dec.decode_i32()".to_string(),
            PrimitiveType::UnsignedLong | PrimitiveType::UInt32 | PrimitiveType::WChar => {
                "dec.decode_u32()".to_string()
            }
            PrimitiveType::LongLong | PrimitiveType::Int64 => "dec.decode_i64()".to_string(),
            PrimitiveType::UnsignedLongLong | PrimitiveType::UInt64 => {
                "dec.decode_u64()".to_string()
            }
            PrimitiveType::Float => "dec.decode_f32()".to_string(),
            PrimitiveType::Double | PrimitiveType::LongDouble => "dec.decode_f64()".to_string(),
            PrimitiveType::String | PrimitiveType::WString => "dec.decode_string()".to_string(),
            _ => "Default::default() /* unsupported */".to_string(),
        }
    }

    /// Generate `compute_key()` method for @key fields
    ///
    /// Returns a 16-byte key hash computed from @key fields using FNV-1a.
    fn generate_compute_key_method(s: &Struct) -> String {
        let mut output = String::new();

        // Find @key fields with their types
        let key_fields: Vec<(&str, &IdlType)> = s
            .fields
            .iter()
            .filter(|f| f.annotations.iter().any(|a| matches!(a, Annotation::Key)))
            .map(|f| (f.name.as_str(), &f.field_type))
            .collect();

        let has_key = !key_fields.is_empty();

        output
            .push_str("\n    /// Compute instance key hash from @key fields (FNV-1a, 16 bytes)\n");
        output.push_str("    #[must_use]\n");
        output.push_str("    pub fn compute_key(&self) -> [u8; 16] {\n");

        if has_key {
            output.push_str("        // FNV-1a hash of @key fields\n");
            output.push_str("        let mut hash: u64 = 14695981039346656037;\n");
            output.push_str("        const PRIME: u64 = 1099511628211;\n\n");

            for (field, field_type) in &key_fields {
                Self::push_fmt(
                    &mut output,
                    format_args!("        // Hash @key field: {}\n", field),
                );
                // Check if field is a string type (primitive String/WString or bounded string)
                let is_string = matches!(
                    field_type,
                    IdlType::Primitive(PrimitiveType::String | PrimitiveType::WString)
                ) || matches!(
                    field_type,
                    IdlType::Sequence { inner, .. }
                        if matches!(**inner, IdlType::Primitive(PrimitiveType::Char | PrimitiveType::WChar))
                );
                if is_string {
                    Self::push_fmt(
                        &mut output,
                        format_args!("        for &b in self.{}.as_bytes() {{\n", field),
                    );
                } else {
                    Self::push_fmt(
                        &mut output,
                        format_args!("        for b in self.{}.to_le_bytes() {{\n", field),
                    );
                }
                output.push_str("            hash ^= u64::from(b);\n");
                output.push_str("            hash = hash.wrapping_mul(PRIME);\n");
                output.push_str("        }\n\n");
            }

            output.push_str("        // Expand to 16 bytes\n");
            output.push_str("        let mut key = [0u8; 16];\n");
            output.push_str("        key[..8].copy_from_slice(&hash.to_le_bytes());\n");
            output.push_str("        hash = hash.wrapping_mul(PRIME);\n");
            output.push_str("        key[8..].copy_from_slice(&hash.to_le_bytes());\n");
            output.push_str("        key\n");
        } else {
            output.push_str("        // No @key fields - return zeroed hash\n");
            output.push_str("        [0u8; 16]\n");
        }

        output.push_str("    }\n");
        output
    }
}
