// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) 2025-2026 naskel.com

//! Rust code generator
//!
//! Generates idiomatic Rust code from IDL

use crate::ast::{Definition, IdlFile};
use crate::codegen::CodeGenerator;
use crate::error::Result;

mod bitmasks;
mod bitsets;
mod dds_trait;
mod decode;
mod decode_containers;
mod encode;
mod encode_containers;
mod enums;
mod fixed;
pub(crate) mod helpers;
mod structs;
mod typedefs;
mod unions;

#[cfg(test)]
mod tests;

pub(crate) use helpers::push_fmt;
use helpers::uses_fixed;

/// Serde rename style for JSON serialization
#[derive(Clone, Copy, Debug, Default)]
pub enum SerdeRename {
    /// No rename (native Rust style)
    #[default]
    None,
    /// camelCase (JavaScript/TypeScript)
    Camel,
    /// `PascalCase` (C#/.NET)
    Pascal,
    /// kebab-case
    Kebab,
}

/// Generates Rust binding code with CDR2 serialization helpers.
pub struct RustGenerator {
    indent_level: usize,
    /// Add serde derives to generated types
    pub(crate) serde: bool,
    /// Serde rename style
    pub(crate) serde_rename: SerdeRename,
}

impl RustGenerator {
    /// Creates a new Rust generator.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            indent_level: 0,
            serde: false,
            serde_rename: SerdeRename::None,
        }
    }

    /// Creates a new Rust generator with serde support.
    #[must_use]
    pub const fn with_serde(serde_rename: SerdeRename) -> Self {
        Self {
            indent_level: 0,
            serde: true,
            serde_rename,
        }
    }

    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }
}

impl Default for RustGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl RustGenerator {
    /// Returns the serde derive string if serde is enabled
    pub(crate) const fn serde_derive(&self) -> &'static str {
        if self.serde {
            ", serde::Serialize, serde::Deserialize"
        } else {
            ""
        }
    }

    /// Returns the serde `rename_all` attribute for enums
    pub(crate) const fn serde_rename_attr(&self) -> &'static str {
        if !self.serde {
            return "";
        }
        match self.serde_rename {
            SerdeRename::None => "",
            SerdeRename::Camel => "#[serde(rename_all = \"camelCase\")]\n",
            SerdeRename::Pascal => "#[serde(rename_all = \"PascalCase\")]\n",
            SerdeRename::Kebab => "#[serde(rename_all = \"kebab-case\")]\n",
        }
    }
}

impl CodeGenerator for RustGenerator {
    fn generate(&self, ast: &IdlFile) -> Result<String> {
        let mut output = String::new();

        // Track mutable/appendable types for PL_CDR2 generation.
        let mutables = helpers::collect_mutable_types(ast);
        helpers::set_mutable_types(mutables);

        // Build type definition index for XTypes inline TypeObject generation.
        helpers::set_type_defs(ast);

        // Header
        output.push_str("// Generated by hddsgen v");
        output.push_str(env!("HDDS_VERSION"));
        output.push('\n');
        output.push_str("// DO NOT EDIT\n");
        output.push_str("// Compatible with include!() macro\n\n");

        // Phase 7a: Import CDR2 traits from hdds crate
        output.push_str("use hdds::{Cdr2Encode, Cdr2Decode, CdrError};\n\n");

        // NOTE: Vec/HashMap/Array trait impls are in hdds crate, not generated here
        // This avoids orphan rule violations (E0117)

        // Prelude if certain features are used
        if uses_fixed(ast) {
            Self::emit_fixed_support(&mut output);
            output.push('\n');
        }

        // Generate definitions (recursive for nested modules)
        self.generate_definitions(&mut output, &ast.definitions, &[], "");

        Ok(output)
    }
}

impl RustGenerator {
    /// Recursively generate code for a list of definitions.
    ///
    /// `module_path` tracks the current module nesting (e.g., `["my_mod", "inner"]`)
    /// for FQN generation. `indent` is the current indentation prefix.
    fn generate_definitions(
        &self,
        output: &mut String,
        definitions: &[Definition],
        module_path: &[&str],
        indent: &str,
    ) {
        // Build FQN prefix for struct type names (e.g., "my_mod::inner::")
        let module_name = if module_path.is_empty() {
            None
        } else {
            Some(module_path.join("::"))
        };

        // Collect enum names for CDR2 alignment: Named enums need padding,
        // Named structs self-align their internal fields (no outer padding).
        let enum_names: Vec<&str> = definitions
            .iter()
            .filter_map(|d| match d {
                Definition::Enum(e) => Some(e.name.as_str()),
                _ => None,
            })
            .collect();

        for def in definitions {
            match def {
                Definition::Module(m) => {
                    push_fmt(output, format_args!("{indent}pub mod {name} {{\n", name = m.name));
                    push_fmt(output, format_args!("{indent}    use super::*;\n\n"));
                    // Recurse into nested module
                    let mut nested_path: Vec<&str> = module_path.to_vec();
                    nested_path.push(&m.name);
                    let nested_indent = format!("{indent}    ");
                    self.generate_definitions(output, &m.definitions, &nested_path, &nested_indent);
                    push_fmt(output, format_args!("{indent}}}\n\n"));
                }
                Definition::Struct(s) => {
                    let code = self.generate_struct_with_module(s, module_name.as_deref(), &enum_names);
                    if indent.is_empty() {
                        output.push_str(&code);
                    } else {
                        push_fmt(output, format_args!("{indent}{}", code.replace('\n', &format!("\n{indent}"))));
                    }
                }
                Definition::Enum(e) => {
                    let code = self.generate_enum(e);
                    if indent.is_empty() {
                        output.push_str(&code);
                    } else {
                        push_fmt(output, format_args!("{indent}{}", code.replace('\n', &format!("\n{indent}"))));
                    }
                }
                Definition::Typedef(t) => {
                    let code = self.generate_typedef(t);
                    if indent.is_empty() {
                        output.push_str(&code);
                    } else {
                        push_fmt(output, format_args!("{indent}{code}"));
                    }
                }
                Definition::Union(u) => {
                    let code = self.generate_union(u);
                    if indent.is_empty() {
                        output.push_str(&code);
                    } else {
                        push_fmt(output, format_args!("{indent}{}", code.replace('\n', &format!("\n{indent}"))));
                    }
                }
                Definition::Bitset(b) => {
                    let code = self.generate_bitset(b);
                    if indent.is_empty() {
                        output.push_str(&code);
                    } else {
                        push_fmt(output, format_args!("{indent}{}", code.replace('\n', &format!("\n{indent}"))));
                    }
                }
                Definition::Bitmask(bm) => {
                    let code = self.generate_bitmask(bm);
                    if indent.is_empty() {
                        output.push_str(&code);
                    } else {
                        push_fmt(output, format_args!("{indent}{}", code.replace('\n', &format!("\n{indent}"))));
                    }
                }
                _ => {}
            }
        }
    }
}
