// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) 2025-2026 naskel.com

//! Rust code generator
//!
//! Generates idiomatic Rust code from IDL

use crate::ast::{Definition, IdlFile};
use crate::codegen::CodeGenerator;
use crate::error::Result;

mod bitmasks;
mod bitsets;
mod dds_trait;
mod decode;
mod decode_containers;
mod encode;
mod encode_containers;
mod enums;
mod fixed;
pub(crate) mod helpers;
mod structs;
mod typedefs;
mod unions;

#[cfg(test)]
mod tests;

pub(crate) use helpers::push_fmt;
use helpers::uses_fixed;

/// Serde rename style for JSON serialization
#[derive(Clone, Copy, Debug, Default)]
pub enum SerdeRename {
    /// No rename (native Rust style)
    #[default]
    None,
    /// camelCase (JavaScript/TypeScript)
    Camel,
    /// `PascalCase` (C#/.NET)
    Pascal,
    /// kebab-case
    Kebab,
}

/// Generates Rust binding code with CDR2 serialization helpers.
pub struct RustGenerator {
    indent_level: usize,
    /// Add serde derives to generated types
    pub(crate) serde: bool,
    /// Serde rename style
    pub(crate) serde_rename: SerdeRename,
}

impl RustGenerator {
    /// Creates a new Rust generator.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            indent_level: 0,
            serde: false,
            serde_rename: SerdeRename::None,
        }
    }

    /// Creates a new Rust generator with serde support.
    #[must_use]
    pub const fn with_serde(serde_rename: SerdeRename) -> Self {
        Self {
            indent_level: 0,
            serde: true,
            serde_rename,
        }
    }

    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }
}

impl Default for RustGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl RustGenerator {
    /// Returns the serde derive string if serde is enabled
    pub(crate) const fn serde_derive(&self) -> &'static str {
        if self.serde {
            ", serde::Serialize, serde::Deserialize"
        } else {
            ""
        }
    }

    /// Returns the serde `rename_all` attribute for enums
    pub(crate) const fn serde_rename_attr(&self) -> &'static str {
        if !self.serde {
            return "";
        }
        match self.serde_rename {
            SerdeRename::None => "",
            SerdeRename::Camel => "#[serde(rename_all = \"camelCase\")]\n",
            SerdeRename::Pascal => "#[serde(rename_all = \"PascalCase\")]\n",
            SerdeRename::Kebab => "#[serde(rename_all = \"kebab-case\")]\n",
        }
    }
}

impl CodeGenerator for RustGenerator {
    fn generate(&self, ast: &IdlFile) -> Result<String> {
        let mut output = String::new();

        // Track mutable/appendable types for PL_CDR2 generation.
        let mutables = helpers::collect_mutable_types(ast);
        helpers::set_mutable_types(mutables);

        // Build type definition index for XTypes inline TypeObject generation.
        helpers::set_type_defs(ast);

        // Header
        output.push_str("// Generated by hddsgen v");
        output.push_str(env!("HDDS_VERSION"));
        output.push('\n');
        output.push_str("// DO NOT EDIT\n");
        output.push_str("// Compatible with include!() macro\n\n");

        // Phase 7a: Import CDR2 traits from hdds crate
        output.push_str("use hdds::{Cdr2Encode, Cdr2Decode, CdrError};\n\n");

        // NOTE: Vec/HashMap/Array trait impls are in hdds crate, not generated here
        // This avoids orphan rule violations (E0117)

        // Prelude if certain features are used
        if uses_fixed(ast) {
            Self::emit_fixed_support(&mut output);
            output.push('\n');
        }

        // Generate definitions
        for def in &ast.definitions {
            match def {
                Definition::Module(m) => {
                    push_fmt(
                        &mut output,
                        format_args!("pub mod {name} {{\n", name = m.name), // Use original module name (not lowercase)
                    );
                    output.push_str("    use super::*;\n\n");
                    for inner_def in &m.definitions {
                        match inner_def {
                            Definition::Struct(s) => {
                                // Pass module name for FQN generation
                                push_fmt(
                                    &mut output,
                                    format_args!(
                                        "    {}",
                                        self.generate_struct_with_module(s, Some(&m.name))
                                            .replace('\n', "\n    ")
                                    ),
                                );
                            }
                            Definition::Enum(e) => {
                                push_fmt(
                                    &mut output,
                                    format_args!(
                                        "    {}",
                                        self.generate_enum(e).replace('\n', "\n    ")
                                    ),
                                );
                            }
                            Definition::Typedef(t) => {
                                push_fmt(
                                    &mut output,
                                    format_args!("    {}", self.generate_typedef(t)),
                                );
                            }
                            Definition::Union(u) => {
                                push_fmt(
                                    &mut output,
                                    format_args!(
                                        "    {}",
                                        self.generate_union(u).replace('\n', "\n    ")
                                    ),
                                );
                            }
                            Definition::Bitset(b) => {
                                push_fmt(
                                    &mut output,
                                    format_args!(
                                        "    {}",
                                        self.generate_bitset(b).replace('\n', "\n    ")
                                    ),
                                );
                            }
                            Definition::Bitmask(m) => {
                                push_fmt(
                                    &mut output,
                                    format_args!(
                                        "    {}",
                                        self.generate_bitmask(m).replace('\n', "\n    ")
                                    ),
                                );
                            }
                            _ => {}
                        }
                    }
                    output.push_str("}\n\n");
                }
                Definition::Struct(s) => output.push_str(&self.generate_struct(s)),
                Definition::Enum(e) => output.push_str(&self.generate_enum(e)),
                Definition::Typedef(t) => output.push_str(&self.generate_typedef(t)),
                Definition::Union(u) => output.push_str(&self.generate_union(u)),
                Definition::Bitset(b) => output.push_str(&self.generate_bitset(b)),
                Definition::Bitmask(m) => output.push_str(&self.generate_bitmask(m)),
                _ => {}
            }
        }

        Ok(output)
    }
}
